### ISSUE TITLE
Add support for Choices.js

### ISSUE THREAD

**Issue by SamMousa** [surveyjs/custom-widgets#209]
This project: https://github.com/jshjohnson/Choices implements an alternative to Select2 that does not depend on jQuery.

It'd be nice to support this widget!

**Comment by andrewtelnov** [comment]
@SamMousa I tried a demo and find several bugs in Chrome. Plus nobody maintaince it :-( 

Thank you,
Andrew

**Comment by SamMousa** [comment]
That's actually quite recently. I'm using in production, it works better for me than Select2.

I might consider maintaining it. Regardless, are you open to a PR to support it in SurveyJS?
