### ISSUE TITLE
can not set range from 100 - 230 in nouislider

### ISSUE THREAD

**Issue by anaskhanstack** [surveyjs/custom-widgets#216]
![Untitled](https://user-images.githubusercontent.com/45259204/95013869-87cc4080-065c-11eb-8667-50215331f5c8.png)

**Comment by andrewtelnov** [comment]
@anaskhanstack You should set rageMin and rageMax properties.
```js
    {
     "type": "nouislider",
     "name": "question1",
     "rangeMin": 100,
     "rangeMax": 230,
    }

```

Thank you,
Andrew

**Comment by anaskhanstack** [comment]
It worked! Thank you so much brother
