### ISSUE TITLE
Update Input-mask dependency to latest version

### ISSUE THREAD

**Issue by mrheault** [surveyjs/custom-widgets#222]
Specifically to include this fix - https://github.com/RobinHerbots/Inputmask/issues/2285
Loading two separate surveys w/ custom-widgets in two separate vue apps on the same page causes the above input-mask error

`Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "input-mask" has already been used with this registry`

**Comment by OlgaLarina** [comment]
@mrheault 
We have a version of "inputmask": "^5.0.3" written in the dependencies, so try deleting the package-lock.json and reinstalling packages, the latest version package must be installed.
