### ISSUE TITLE
The tooltip get stuck in nouislider

### ISSUE THREAD

**Issue by anaskhanstack** [surveyjs/custom-widgets#232]
![Capture](https://user-images.githubusercontent.com/45259204/100316246-ecac7300-2fdb-11eb-9426-4cd2bf32f7ab.PNG)

When i add tooltio in my slider it get stuck the slider does move but the tool does't move 

when i use cdn, it get fixed, but when i use the min.js file, the issue gets appear again

**Comment by tsv2013** [comment]
Moved to the proper repo

**Comment by tsv2013** [comment]
noislider is a 3rd party library not related to SurveyJS products. We can't answers questions about the code and behavior not related to SurveyJS code.
