### ISSUE TITLE
Autocomplete widget is not working

### ISSUE THREAD

**Issue by Danyshman** [surveyjs/custom-widgets#238]
1. I tried to use autocomplete widget in my project, it did not work (other widgets work fine). Then i tried to clone react quick start from your github repo, autocomplete widget is not working even from your fresh react quick start repo.

**Comment by andrewtelnov** [comment]
@Danyshman Here is [the example](https://codesandbox.io/s/8keg0). You can create a codesandbox project from the most of our examples by clicking "Edit in..." dropdown in the top right corner.

Thank you,
Andrew

**Comment by joker-777** [comment]
@andrewtelnov Hi, I can see the autocomplete widget and it also lets me select some values. But then the results of the survey don't show this selection but only the characters I typed in.

**Comment by tsv2013** [comment]
Fix will be available in the nearest update
