### ISSUE TITLE
unable to add custom widget to creator toolbox 

### ISSUE THREAD

**Issue by sirajansari3** [surveyjs/custom-widgets#239]
[Hi,](url
[textwithbutton.txt](https://github.com/surveyjs/custom-widgets/files/5723714/textwithbutton.txt)
[SurveyCreator.txt](https://github.com/surveyjs/custom-widgets/files/5723715/SurveyCreator.txt)
)
I am trying to add one of the custom widget to survey creator toolbox but getting failed...plz help.
i used surveyjs_react_quickstart to add new widget i m refering below sample
i m referring this example: https://codesandbox.io/s/crazy-rain-3wqj7?file=/src/customwidget.js

**Comment by tsv2013** [comment]
Answered here - https://surveyjs.answerdesk.io/ticket/details/t5959/unable-to-add-custom-widget-to-creator-toolbox
