### ISSUE TITLE
Survey form breaks when we use autocomplete widget with matrixdynamic

### ISSUE THREAD

**Issue by Danyshman** [surveyjs/custom-widgets#240]
When you use matrixdynamic with autocomplete widget, if you use "text" type in matrixdynamic, form throws error. Here is the url for sandbox https://codesandbox.io/s/brave-smoke-oq5s9?file=/src/SurveyComponent.jsx

**Comment by tsv2013** [comment]
Thank you for the sample. We'll take a look.

**Comment by Danyshman** [comment]
When the fix will available?

**Comment by dk981234** [comment]
Hello,

The fix will be available with the next minor update, which will be in the coming days, probably, tomorrow.

Thanks,
Dmitry
SurveyJS Team

**Comment by Danyshman** [comment]
@dk981234 Hello, the fix is not working in latest release 1.8.22. Url to sandbox https://codesandbox.io/s/brave-smoke-oq5s9?file=/src/SurveyComponent.jsx

**Comment by Danyshman** [comment]
@dk981234 How i can pass custom configuration to easy-autocomplete widget?

**Comment by Danyshman** [comment]
@dk981234 Is there any limit to number of choices? Because for 500 long text it does not work, but for 100 of them it works.

**Comment by dk981234** [comment]
Hello,

We've implemented the 'config' property to pass custom configuration to the easy-autocomplete widget. 
For example, you can pass placeholder like this: 
`var json = {
  questions: [
    {
      name: "autocomplete1",
      title: "What car are you driving?",
      type: "text",
      config: {
        placeholder: "Car",
      },
      choices: ["None"],
    },
  ],
};`

The feature will be available with the next minor update next week.

Thanks,
Dmitry
SurveyJS Team
