### ISSUE TITLE
InputMask - Optional mask not working

### ISSUE THREAD

**Issue by net-sanchez** [surveyjs/custom-widgets#242]
type = "text"
inputMask = "phone"
inputFormat = "(99) 9999[9]-9999"

This set up is only with 9 numbers phone but not with 8. On visual it seems to work but as soon as you focus out the value is cleared.

I tried to clearImcomplete: false but it didnt work

I Also noted it is only happening in angular. Jquery seems to work fine

**Comment by stsiushkevich** [comment]
I have a same issue.

https://codesandbox.io/s/51sik?file=/src/SurveyComponent.jsx
