### ISSUE TITLE
Select2 widget initialization in functional component

### ISSUE THREAD

**Issue by VerdonTrigance** [surveyjs/custom-widgets#247]
Hi there.
I found unexpected problems with widget initialization in functional components:
https://codesandbox.io/s/reverent-christian-13hzr?file=/src/SurveyComponent.jsx

How to init select2 widget properly with such approach? Looks like all scripts in place, because I can type:
$("#sq_100i").select2()
in a console and this would work as expected.
But select2 not applied automatically in Survey.Survey component.
What I'm doing wrong?

PS: I also facing with such error:
![image](https://user-images.githubusercontent.com/12109173/111996714-5b817f00-8b2b-11eb-8be7-2a0781a45414.png)
I found this part in file \node_modules\select2\dist\js\select2.js, but it shouldn't loads that way.
It should be like:
```
function (root, jQuery) {
      if (jQuery === undefined) {
        // require('jQuery') returns a factory that requires window to
        // build a jQuery instance, we normalize how we use modules
        // that require this pattern but the window provided is a noop
        // if it's defined (how jquery works)
        if (typeof window !== 'undefined') {
          jQuery = require('jquery');
        }
        else {
          jQuery = require('jquery')(root);
        }
      }
      factory(jQuery);
      return jQuery;
    };
```

**Comment by tsv2013** [comment]
Here is the fixed sample - https://codesandbox.io/s/lucid-wozniak-weem6

**Comment by VerdonTrigance** [comment]
> Here is the fixed sample - https://codesandbox.io/s/lucid-wozniak-weem6

Are you sure it works?
![image](https://user-images.githubusercontent.com/12109173/112113870-6f2ef300-8bc8-11eb-93b7-e313895446af.png)
You probably changed something and press Ctrl+S. This results to updating 'select' properly. But refresh page in right tab again. This not working.

**Comment by tsv2013** [comment]
>This results to updating 'select' properly.
Sorry, but I don't understand you.
Could you spoecify the exact steps to reproduce the issue, the expected and actual result?

**Comment by tsv2013** [comment]
Your screenshot looks ok for me.

**Comment by VerdonTrigance** [comment]
> Your screenshot looks ok for me.

![image](https://user-images.githubusercontent.com/12109173/112118542-87554100-8bcd-11eb-89ed-83df12e1aa90.png)

Here is no active select2 dropdown as you can see.

**Comment by tsv2013** [comment]
One line wasn't saved - https://codesandbox.io/s/lucid-wozniak-weem6?file=/src/SurveyComponent.jsx

![image](https://user-images.githubusercontent.com/3013415/112120511-5d9d1980-8bcf-11eb-9367-ad9b93ef705b.png)

**Comment by VerdonTrigance** [comment]
> One line wasn't saved - https://codesandbox.io/s/lucid-wozniak-weem6?file=/src/SurveyComponent.jsx
> 
> ![image](https://user-images.githubusercontent.com/3013415/112120511-5d9d1980-8bcf-11eb-9367-ad9b93ef705b.png)

Now it works... in sandbox. My project still return TypeError from "PS" part. But I guess it's another topic.
Thanks for helping out.
