### ISSUE TITLE
Bootstrap Datepicker with date range

### ISSUE THREAD

**Issue by ivorycoast** [surveyjs/custom-widgets#252]
### Are you requesting a feature, reporting a bug or asking a question?
Question

### What is the current behavior?
I would like to know if this feature of Bootstrap Datepicker is available?
https://bootstrap-datepicker.readthedocs.io/en/latest/markup.html#date-range

If not, it will be interesting to have that.

### Specify your

* browser: Firefox
* browser version: 87.0
* surveyjs platform (angular or react or jquery or knockout or vue): vue
* surveyjs version: 1.8.39

**Comment by ivorycoast** [comment]
@andrewtelnov thanks for your prompt answer. Do you plan to create this new functionality/custom widget?

Thanls,

Warren

**Comment by tsv2013** [comment]
@ivorycoast Right now - no. You are the first who are asking for it. If this functionality will be requested highly by other customers, we'll reconsider this.

**Comment by ivorycoast** [comment]
Ok fine. Thank you!
