### ISSUE TITLE
Nouislider not showing up on built Android / iOS applications

### ISSUE THREAD

**Issue by treksn** [surveyjs/custom-widgets#256]
We currently have the problem, that the slider (nouislider) is not showing up in the built mobile versions of our application. In the web version, the slider is visible. I figured out, that the slider data is already missing in the survey object, which is created with:

`this.survey = new Survey.Model(this.surveyConfig)`

```
...
{
      "name": "page-29",
      // This part is missing on mobile
      "elements": [
        {
          "type": "nouislider",
          "name": "global07",
          "title": "Headline",
          "isRequired": true,
          "rangeMax": 10,
          "pipsValues": [
            {
              "value": 0,
              "text": "0"
            },
            {
              "value": "100",
              "text": "10"
            }
          ],
          "pipsText": [
            {
              "value": 0,
              "text": "0"
            },
            {
              "value": "100",
              "text": "10"
            }
          ]
        }
      ]
    }
...
```

The object / json structure from this.surveyConfig is identical on web / mobile, but the output from surveyjs which is stored in this.survey is not. When running the app, there is no error message thrown in the logs. Could you maybe give me any hint to fix or work around this problem? 

We are using Angular 10  with Ionic 5. The surveyjs versions are the following:
"survey-angular": "^1.7.8",
"survey-creator": "^1.7.8",
"surveyjs-widgets": "^1.7.8",

**Comment by tsv2013** [comment]
We don't guarantee the 3rd party widgets like slider (nouislider) will work on mobile devices.
