### ISSUE TITLE
EasyAutocomplete doesn't work with goNextPageAutomatic: true

### ISSUE THREAD

**Issue by joker-777** [surveyjs/custom-widgets#266]
Hi, the problem is that you use `onSelectItemEvent` to select the question value instead of `onChooseEvent`. This will automatically evaluate the question when hovering over any of the autocomplete options.
https://github.com/surveyjs/custom-widgets/blob/master/src/easy-autocomplete.js#L77

**Comment by andrewtelnov** [comment]
@joker-777 That you for reporting and for the tip.

Andrew

**Comment by joker-777** [comment]
@andrewtelnov Thanks for fixing this so quickly. I found another problem that was much more complicated. Using `goNextPageAutomatic: true`, a text input field will evaluate automatically `onBlur` event which also happens when you click on one of the easyAutocomplete options. This means it automatically uses the text you typed in instead of the option you clicked on.
My workaround, for now, is to overwrite `question.correctValueType` but I hope there is/will be a more elegant solution.

```js
question.correctValueType = () => {
  if ($el.getSelectedItemData() < 0) return
  return $el.getSelectedItemData()
}   
```

**Comment by andrewtelnov** [comment]
@joker-777 I believe it makes sense just to remove `goNextPageAutomatic` functionality support from this widget. Easy complete fire `onBlue` and we have to apply the value. We can't use corretValueType, at first it is protected, but it is not the main point. Easy complete allows to enter any text and we will kill this functionality in this case.
Plus, why don't you use dataList property of the text question. If works pretty similar out of the box. Here is [the example](https://plnkr.co/edit/bBoLVtz6cEvmO5fY).

Thank you,
Andrew

**Comment by joker-777** [comment]
You are probably right. I also realized that the select2 field is actually a much better fit for my use case.
