### ISSUE TITLE
Bootstrap-datepicker - Unable to set date with the widget

### ISSUE THREAD

**Issue by mikekidder** [surveyjs/custom-widgets#267]
Assumption: The enhancement to datepicker in #257 released in milestone 1.8.50 breaks the ability to select a date from the widget.

From the online examples:
https://surveyjs.io/Examples/Library?id=custom-widget-bootstrapdatepicker&platform=Knockoutjs&theme=modern

Everything is greyed out and cannot be selected.

Here is working sample (Plunker) with version 1.8.49:
https://plnkr.co/edit/XMWrXqUyGXghFw1A

**Comment by andrewtelnov** [comment]
@mikekidder I have fixed it in the library. Here is [the related issue](https://github.com/surveyjs/survey-library/issues/3162).
bootstrap datepicker doesn't understand endDate: '2999-12-31'. The standard input with inputType: "date" works fine.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@mikekidder My fix in the library was incorrect. We have requested to set max date to '2999-31-12' by default.
I added a work-around for bootstrap date picker since it works incorrectly for this max date.

Thank you,
Andrew
