### ISSUE TITLE
noUISlider question improvements

### ISSUE THREAD

**Issue by tsv2013** [surveyjs/custom-widgets#277]
See the https://surveyjs.answerdesk.io/ticket/details/t8087/nouislider-questions-and-fixes thread for more details

Need to fix:

- [x] The pips don't match the number being chosen
- [x] In the middle of the screen in the editor, where the questions are listed, the slider doesn't automatically update on changes
- [x] The options for positioning pips are not explained too well
- [x] Add tests 
- [x] Implement `pipsValues` property observable

**Comment by andresfelipe9619** [comment]
Hello guys, 

We really love what you have made, this is such an amazing library.

We have been using surveys for a while but now that we are upgrading to the latest version seems like there is an error using the nouislider 
![image](https://user-images.githubusercontent.com/26072242/142489973-03d8a347-c704-4c01-b5f2-c864ec621a1e.png)
After a good time searching on the web and no results I decided to look into the source code, seems like the function is not at the scope of the will unmount and only declared inside the afterRender function
![image](https://user-images.githubusercontent.com/26072242/142490576-da8b9de9-ffa4-4174-b55d-1d804fe65f2a.png)

Hope this helps to solve the issue a bit faster, thanks!

**Comment by ST-1580** [comment]
Hello, @andresfelipe9619 

We've fixed this issue. This functionality is available now (from `v1.8.79`)
