### ISSUE TITLE
Clickeable map widget (Question)

### ISSUE THREAD

**Issue by BenjaGramsch** [surveyjs/custom-widgets#294]
### Are you requesting a feature, reporting a bug or ask a question?
Question

I am looking to add a widget with a map (from Google Maps or Open Street Maps) where the user can write the address or click on the map and returns the coordinates, does something like that exists? I have been looking without luck.

I would like to look similar to this:
![image](https://user-images.githubusercontent.com/57944945/154972445-d97b3fca-f675-4fbe-a5d9-9939008ceac7.png)

Thanks!

**Comment by tsv2013** [comment]
I believe you can find the answer in this thread - https://surveyjs.answerdesk.io/ticket/details/t4081/address-form-with-autocomplete-api#

I've created a live plunker sample with Google Maps AutoComplete API custom widget
https://plnkr.co/edit/ztVbxFqElzFxlBJj
You need to change the YOUR_API_KEY_HERE string to your API key
See the https://developers.google.com/maps/documentation/javascript/examples/places-autocomplete?csw=1#maps_places_autocomplete-javascript tutorial for more details
