### ISSUE TITLE
jQuery UI Calendar Widget: minDate / maxDate no longer working

### ISSUE THREAD

**Issue by joshcampbell191** [surveyjs/custom-widgets#301]
### Are you requesting a feature, reporting a bug or asking a question?
Reporting a Bug

### What is the current behavior?
The jQuery UI Calendar widget no longer ignores minDate / maxDate settings.

### What is the expected behavior?
The jQuery UI Calendar widget should allow the minDate / maxDate settings via the `config` / `minDate` / `maxDate` properties.

This appears to be regression as it was last working in 1.8.49.

### How would you reproduce the current behavior (if this is a bug)?
1. Create a survey with a datepicker widget that has a minDate / maxDate.
2. Open the jQuery UI calendar widget.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://plnkr.co/edit/w2WNo464gDSt8BEu

Test code

```
Survey
    .StylesManager
    .applyTheme("modern");

var json = {
    "elements": [
        {
            "name": "date",
            "type": "datepicker",
            "inputType": "date",
            "title": "Your favorite date:",
            "dateFormat": "mm/dd/yy",
            "isRequired": true,
            "config": {
                "maxDate": 0
            }
        }
    ]
};

window.survey = new Survey.Model(json);

survey
    .onComplete
    .add(function (sender) {
        document
            .querySelector('#surveyResult')
            .textContent = "Result JSON:\n" + JSON.stringify(sender.data, null, 3);
    });

$("#surveyElement").Survey({model: survey});
```

### Specify your

* browser: Microsft Edge
* browser version: 99.0.1150.46
* surveyjs platform (angular or react or jquery or knockout or vue): jQuery / Vue
* surveyjs version: 1.9.20

**Comment by andrewtelnov** [comment]
@joshcampbell191 We missed this one. Sorry about it.
We have fixed this issue some time ago. Please use min/max and minValueExpression/maxValueExpression
Here is [the example](https://plnkr.co/edit/1bnuQeDdbUnIf20c).

Thank you,
Andrew
