### ISSUE TITLE
Request to add inputmask dateformating in datepicker

### ISSUE THREAD

**Issue by paragkulkarni** [surveyjs/custom-widgets#304]
InputMask is not working with datepicker. Also dateformat is not working. So please add some feature. 
Scenario - when we don't set date, UI showing the textbox empty
![image](https://user-images.githubusercontent.com/29193843/161714228-b6ad8735-c3f0-4b36-8b3e-7dd97c99f7a3.png)
Refer this image and we are also not feature of masking. So it is really cumbersome for to work. I request you to please add some feature in datepicker

**Comment by JaneGaid** [comment]
Hello,
You can create a simple text question and set its [inputType](https://surveyjs.io/Documentation/Library?id=questiontextmodel#inputType) to `date`. Now, the text box will display the date input mask:
![image](https://user-images.githubusercontent.com/22372972/186909605-d2b0dbd1-fad4-461b-aa11-3391585218d2.png)
