### ISSUE TITLE
decimal inputmask align to left

### ISSUE THREAD

**Issue by paragkulkarni** [surveyjs/custom-widgets#306]
How to make inputmask with decimal align to left.

Help will be appreciated

**Comment by JaneGaid** [comment]
Hello,
For the record: SurveyJS uses the https://unpkg.com/inputmask@5.0.3/dist/inputmask.js jQuery plugin to implement input mask functionality. 

You can use your browser tools to explore which CSS styles are used by a given component. For example, you can apply the following CSS to change the text-alignment of the decimal input using the input Id.
```
#sq_100i{
  text-align: left !important;
}
```
