### ISSUE TITLE
Numeric Validation doesn't work when a custom decimal separator (numericRadixPoint) is used

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/custom-widgets#331]
Original issue: [T11866 - Inputmask - A numeric validator does not validate the field if we have "," as a decimal separator](https://surveyjs.answerdesk.io/internal/ticket/details/T11866).
***
[Example](https://codesandbox.io/s/nice-darkness-0nhorh?file=/src/SurveyComponent.jsx:551-668)

Specify a custom decimal part separator:
```
SurveyCore.CustomWidgetCollection.Instance.getCustomWidgetByName(
  "maskedit"
).widgetJson.numericRadixPoint = ",";
```
Configure numeric validation:
```
validators: [
        {
          type: "numeric",
          text:
            "Ange ett numeriskt värde och värdet får inte överstiga 9999999999.",
          minValue: 0,
          maxValue: 9999999999
        }
]
```
It works OK if the entered value doens't contain a decimal part. To reproduce the issue, enter a value with a decimal part. Validation doesn't recognize the value as numeric:
![image](https://user-images.githubusercontent.com/22372972/215421301-2cef8d07-1172-4f17-81be-a3ac82e35f29.png)

**Comment by andrewtelnov** [comment]
The issue was fixed in SurveyJS Library. Here is [the related issue](https://github.com/surveyjs/survey-library/issues/5612).

Thank you,
Andrew
